# Generated by Django 4.2 on 2023-04-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismapp', '0002_logincard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phn', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Logincard',
        ),
        migrations.AddField(
            model_name='tourismcard',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
