# Generated by Django 4.2 on 2023-04-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourismapp', '0003_booking_delete_logincard_tourismcard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Bookingdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourismapp.tourismcard'),
        ),
    ]
