# Generated by Django 4.2 on 2023-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismapp', '0004_booking_bookingdate_booking_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Bookingdate',
            field=models.DateField(null=True),
        ),
    ]
